=== tmancinelli/digitaltext2022/XML/poesia_ita.dtd
<!ENTITY % Contenuti "titolo?, autore?, para+, firma*">

<!ELEMENT libro (introduzione*,corpo+, epilogo*, indice*)>
<!ELEMENT introduzione (%Contenuti;)>
<!ELEMENT corpo (titolo*,(poesia|prosa)+)>
<!ELEMENT epilogo (%Contenuti;)>
<!ELEMENT indice ANY>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT autore (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT poesia (titolo?,strofa+)>
<!ELEMENT strofa (verso+)>
<!ELEMENT verso (#PCDATA)>
<!ATTLIST verso metro CDATA #REQUIRED>
<!ELEMENT prosa (#PCDATA)>
<!ELEMENT firma (#PCDATA)>

=== tmancinelli/digitaltext2022/XML/machado_studenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro SYSTEM 'poesia_ita.dtd'>
<libro>
    <introduzione>
        <para> Por su libro Vida de Don Quijote y Sancho.</para>
    </introduzione>
    <corpo>
        <poesia>
            <titolo>A DON MIGUEL DE UNAMUNO</titolo>
            <strofa>
                <verso>Este donquijotesco</verso>
                <verso>don Miguel de Unamuno, fuerte vasco,</verso>
                <verso>lleva el arnés grotesco</verso>
                <verso>y el irrisorio casco</verso>
                <verso>del buen manchego. Don Miguel camina,</verso>
                <verso>jinete de quimérica montura,</verso>
                <verso>metiendo espuela de oro a su locura,</verso>
                <verso>sin miedo de la lengua que malsina.</verso>
            </strofa>
        </poesia>
    </corpo>
    <epilogo>
        <para/>
        <firma>Antonio Machado</firma>
    </epilogo>
</libro>
